// src/app/header/header.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {Header} from '../@core/interfaces/Header';
import {GlobalModel} from '../@core/models/global.model';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor(
    public globals: GlobalModel,
  ) {
  }

  ngOnInit(): void {
  }
}

<div class="border-margin-padding-rounded flex-column">
    <mat-form-field>
    <mat-label>Dokument Titel:</mat-label>
        <input matInput [(ngModel)]="globals.header.documentTitle"/>
    </mat-form-field>
    <mat-form-field>    
    <mat-label>Organisation:</mat-label>
        <input matInput [(ngModel)]="globals.header.organisation"/>
    </mat-form-field>
    <mat-form-field>
        <mat-label>Lab/Kurs:</mat-label>
        <input matInput [(ngModel)]="globals.header.labCourse"/>
    </mat-form-field>
    <mat-form-field>
        <mat-label>Name:</mat-label>
        <input matInput [(ngModel)]="globals.header.name"/>
    </mat-form-field>
    <mat-form-field>
        <mat-label>Platz:</mat-label>
        <input matInput [(ngModel)]="globals.header.place"/>
    </mat-form-field>
    <mat-form-field>
        <mat-label>Assistent/in:</mat-label>
        <input matInput [(ngModel)]="globals.header.assistant"/>
    </mat-form-field>
    <mat-form-field>
        <mat-label>Herzustellendes Präparat:</mat-label>
        <input matInput [(ngModel)]="globals.header.preparation"/>
    </mat-form-field>
</div>

// src/app/onepager/Header.tsx
import { TextField } from '@material-ui/core';
import * as React from 'react';
import UIStore from '../stores/Store';
import useItemStyle from '../styles/onepager/Items';
import DefaultPanel from './DefaultPanel';

export default function Header(): React.ReactElement {
    const classes = useItemStyle();

    const store = UIStore.useState();

    return (
        <DefaultPanel>
            <TextField className={classes.input} label={'Document Titel'} value={store.documentTitle} onChange={(ev) => {
                UIStore.update((s) => {
                    s.documentTitle = ev.currentTarget.value;
                });
            }} />
            <TextField className={classes.input} label={'Organistation'} value={store.organisation} onChange={(ev) => {
                UIStore.update((s) => {
                    s.organisation = ev.currentTarget.value;
                });
            }} />
            <TextField className={classes.input} label={'Lab/Kurs'} value={store.labCourse} onChange={(ev) => {
                UIStore.update((s) => {
                    s.labCourse = ev.currentTarget.value;
                });
            }} />
            <TextField className={classes.input} label={'Name'} value={store.name} onChange={(ev) => {
                UIStore.update((s) => {
                    s.name = ev.currentTarget.value;
                });
            }} />
            <TextField className={classes.input} label={'Platz'} value={store.place} onChange={(ev) => {
                UIStore.update((s) => {
                    s.place = ev.currentTarget.value;
                });
            }} />
            <TextField className={classes.input} label={'Assistent/in'} value={store.assistant} onChange={(ev) => {
                UIStore.update((s) => {
                    s.assistant = ev.currentTarget.value;
                });
            }} />
            <TextField className={classes.input} label={'Versuch/Herzustellendes Präparat'} value={store.preparation} onChange={(ev) => {
                UIStore.update((s) => {
                    s.preparation = ev.currentTarget.value;
                });
            }} />
        </DefaultPanel>
    );
}
